@startuml

skinparam linetype ortho
skinparam minClassWidth 200
skinparam class {
	BackgroundColor White
	ArrowColor Black
	BorderColor Black
}

abstract class "Processing()" as pAbstract {
}

class "Verb_ing()" as pConcrete <<Present Participle>> {
}

pAbstract "1" o-u- "0..*" pAbstract
pAbstract <|-- pConcrete

footer **Processing()** Class Diagram - Abstract \n(C) DSP-Crowd Electronics GmbH

@enduml

